### ISSUE TITLE
Check Word document for Accessibility issue

### ISSUE THREAD

**Issue by skounis** [eu-digital-identity-wallet/architecture-and-reference-framework#4]
## How to Check
1. Open the document with MS Word
2. Enable the "Accessibility" option by clicking on it in the status bar  
![image](https://user-images.githubusercontent.com/690575/218064296-55cf8828-1b09-4cdd-8a5a-ed45a0ba6996.png)
3. Check the Inspection results in the sidebar 

![image](https://user-images.githubusercontent.com/690575/218064457-e4a86242-73be-43d8-b3cf-dfc854f2c354.png)

## Tasks
1. [x] Add descriptions to the images
2. [x] Add headers to the tables 
3. [x] Review low-contrast issues
4. [x] Prepare reference `.docx` and use it for style.
